spring.application.name=assistencesystem

# PostgreSQL Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/assistencedb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Logging
logging.level.root=WARN
logging.level.com.miguel=DEBUG
logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Error details
server.error.include-stacktrace=always
server.error.include-exception=true
server.error.include-message=always

#Security Configuration
security.session.timeout=30m
security.session.refresh-threshold=10m
