package com.miguel.assistencesystem.domain.audit;

public enum AuditAction {
	CLIENT_REGISTERED,
	CLIENT_UPDATED,

	PRODUCT_IDENTIFIED,
	PRODUCT_INSTALLED_IDENTIFIED,
	PRODUCT_INSTALLED_UNIDENTIFIED,

	SERVICE_ORDER_OPENED,
	SERVICE_ORDER_STATUS_CHANGED,

	EMPLOYEE_ACCOUNT_CREATED
}
