package com.miguel.assistencesystem.domain.enums;

public enum DomainErrorCode {
		INVALID_CREDENTIALS,
		UNAUTHENTICATED,
		CLIENT_NOT_FOUND,
		DUPLICATE_CLIENT,
		INVALID_CLIENT_DATA,
		DUPLICATE_EMPLOYEE,
		INSUFFICIENT_PERMISSIONS,
		INVALID_EMPLOYEE_DATA,
		INVALID_PRODUCT_DATA,
		INVALID_PRODUCT_STATE,
		PRODUCT_NOT_FOUND,
		INVALID_SERVICE_ORDER_DATA,
		INVALID_SERVICE_ORDER_STATUS,
		SERVICE_ORDER_ALREADY_OPEN,
		SERVICE_ORDER_NOT_FOUND
}
